//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int UserRowId { get; set; }
        public string LoginID { get; set; }
        public string Name { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> Cby { get; set; }
        public Nullable<System.DateTime> Cdt { get; set; }
        public Nullable<int> Mby { get; set; }
        public Nullable<System.DateTime> Mdt { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
